#! /usr/bin/env python
# encoding: utf-8

import os

lib = bld.shlib(
  vala_defines=['DEBUG'],
  features='c cshlib',
  target='features',
  vapi_dirs='../../vapi',
  uselib='DIODON PEAS PEASGTK',
  install_binding=False,
  packages='diodon libpeas-1.0 libpeas-gtk-1.0',
  source=bld.path.ant_glob(incl='**/*.vala'))

lib.install_path = os.path.join(bld.env['PLUGINS_DIR'], lib.target)

bld.install_files(lib.install_path, 'features.plugin')
bld.install_files('/usr/share/icons/hicolor/16x16/actions', 'diodon-pin-up.svg')
bld.install_files('/usr/share/icons/hicolor/16x16/actions', 'diodon-pin-down.svg')
bld.install_files('/usr/share/icons/hicolor/16x16/actions', 'diodon-edit.svg')
bld.install_files('/usr/share/icons/hicolor/16x16/actions', 'diodon-delete.svg')

task = bld.new_task_gen(features = 'glib2')
task.add_settings_schemas('net.launchpad.Diodon.Features.gschema.xml')
